
CHAINS_DATA = {
    'ethereum': {'explorer': 'https://etherscan.io/tx/'},
    'base': {'explorer': 'https://basescan.org/tx/'},
    'arbitrum': {'explorer': 'https://arbiscan.io/tx/'},
    'zksync': {'explorer': 'https://era.zksync.network/tx/'},
    'optimism': {'explorer': 'https://optimistic.etherscan.io/tx/'},
    'scroll': {'explorer': 'https://scrollscan.com/tx/'},
    'nova': {'explorer': 'https://nova-explorer.arbitrum.io/tx/'},
    'linea': {'explorer': 'https://lineascan.build/tx/'},
    'bsc': {'explorer': 'https://bscscan.com/tx/'},
    'polygon': {'explorer': 'https://polygonscan.com/tx/'},
    'celo': {'explorer': 'https://celoscan.io/tx/'},
    'moonbeam': {'explorer': 'https://moonscan.io/tx/'},
    'fantom': {'explorer': 'https://ftmscan.com/tx/'},
    'avax': {'explorer': 'https://snowtrace.io/tx/'},
    'ronin': {'explorer': 'https://app.roninchain.com/tx/'},
    'unichain': {'explorer': 'https://uniscan.xyz/tx/'},
    "blast": {'explorer': 'https://blastscan.io/tx/'},
    "zora": {'explorer': 'https://zorascan.xyz/tx/'},
    "b3": {'explorer': 'https://explorer.b3.fun/tx/'},
    "flow": {'explorer': 'https://evm.flowscan.io/tx/'},
    "ape": {'explorer': 'https://apescan.io/tx/'},
    "bera": {'explorer': 'https://berascan.com/tx/'},
    "soneium": {'explorer': 'https://soneium.blockscout.com/tx/'},
    "abstract": {'explorer': 'https://abscan.org/tx/'},
    "camp": {'explorer': 'https://basecamp.cloud.blockscout.com/tx/'},
}

CHAIN_TOKENS = {
    "base": "ETH",
    "blast": "ETH",
    "sei": "SEI",
    "bsc": "BNB",
    "ethereum": "ETH",
    "klaytn": "KLAY",
    "matic": "MATIC",
    "solana": "SOL",
    "arbitrum": "ETH",
    "avax": "AVAX",
    "optimism": "ETH",
    "linea": "ETH",
    "zora": "ETH",
    "b3": "ETH",
    "flow": "FLOW",
    "ape": "APE",
    "soneium": "ETH",
    "ronin": "RON",
    "bera": "BERA",
    "unichain": "ETH",
    "abstract": "ETH",
    "camp": "CAMP",
    "polygon": "MATIC",
    "fantom": "FTM",
}

TOKEN_ADDRESSES = {
    'linea'  : {
        "LINEA": "0x1789e0043623282D5DCc7F213d703C6D8BAfBB04",
    },
}
